apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "videoprocessor.fullname" . }}
  namespace: {{ .Values.namespace.name | default "kutcut" }}
  labels:
    {{- include "videoprocessor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "videoprocessor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "videoprocessor.selectorLabels" . | nindent 8 }}
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: {{ include "videoprocessor.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: RABBITMQ_QUEUE_VIDEO_PROCESS
              value: {{ .Values.config.rabbitmq.queueVideoProcess | quote }}
            - name: RABBITMQ_QUEUE_VIDEO_PROCESS_COMPLETED
              value: {{ .Values.config.rabbitmq.queueVideoProcessCompleted | quote }}
            - name: RABBITMQ_PREFETCH_COUNT
              value: {{ .Values.config.rabbitmq.prefetchCount | quote }}
            - name: BLOB_STORAGE_CONTAINER_NAME
              value: {{ .Values.config.blobStorage.containerName | quote }}
            
            # Pegando usuário e senha do segredo criado pelo CSI Driver
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "videoprocessor.fullname" . }}-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "videoprocessor.fullname" . }}-secret
                  key: RABBITMQ_PASS
            - name: BLOB_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "videoprocessor.fullname" . }}-secret
                  key: BLOB_STORAGE_CONNECTION_STRING

            # Montando a URL final para o Python
            - name: RABBITMQ_URL
              value: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASS)@{{ .Values.config.rabbitmq.host }}:{{ .Values.config.rabbitmq.port }}/"

          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.keyVault.enabled }}
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
            {{- end }}
      volumes:
        {{- if .Values.keyVault.enabled }}
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "videoprocessor.fullname" . }}-kv
        {{- end }}
