{{- if .Values.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "videoprocessor.fullname" . }}-kv
  namespace: {{ .Values.namespace.name | default "kutcut" }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.keyVault.clientId | quote }}
    keyvaultName: {{ .Values.keyVault.name | quote }}
    tenantId: {{ .Values.keyVault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: rabbitmq-username
          objectType: secret
          alias: RABBITMQ_USER
        - |
          objectName: rabbitmq-password
          objectType: secret
          alias: RABBITMQ_PASS
        - |
          objectName: azure-blob-connection-string
          objectType: secret
          alias: BLOB_STORAGE_CONNECTION_STRING
  secretObjects:
    - secretName: {{ include "videoprocessor.fullname" . }}-secret
      type: Opaque
      data:
        - objectName: rabbitmq-username
          key: RABBITMQ_USER
        - objectName: rabbitmq-password
          key: RABBITMQ_PASS
        - objectName: azure-blob-connection-string
          key: BLOB_STORAGE_CONNECTION_STRING
{{- end }}
