apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "videoprocessor.fullname" . }}
  namespace: {{ .Values.namespace.name | default "kutcut" }}
  labels:
    {{- include "videoprocessor.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.keyVault.clientId | quote }}
